services:
  - type: web
    name: ai-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
